### ISSUE TITLE
For other ed

### ISSUE THREAD

**Issue by Alexey-T** [xdrop/Hungry-Backspace#1]
Hi. Nice idea. Maybe possible to port to CudaText (py API)?

**Comment by xdrop** [comment]
Hi and thanks for the suggestion, but I feel a CudaText user would be more appropriate to port this as I've never used the editor before. I'll keep this in mind however if I ever get some time and decide to port it to other editors :+1:

**Comment by Alexey-T** [comment]
sorry; I see that Bksp on linestart, does jump to indent; feature of Cuda (shamed)
