### ISSUE TITLE
[Feature request] No backspace if carriage in line begin

### ISSUE THREAD

**Issue by Kristinita** [xdrop/Hungry-Backspace#2]
### 1. Request

It would be nice, if you add command to run backspace command only if carriage is not in line beginning.

### 2. Justification

I record macros. I need same behavior if I have text before carriage and if my carriage in beginning of line, because now I can get different macros results.

### 3. Actual behavior

If I run native Sublime Text `Delete to Hard EOL` macro (<kbd>Ctrl+Shift+Backspace</kbd> in Windows by default):

![Actual behavior](http://i.imgur.com/cX2CuRE.gif)

I have same behavior if I run native Sublime Text `Delete to EOL` macro.

### 4. Desirable behavior

+ If I have text before carriage, all text before carriage was deleted, carriage move to beginning of line.
+ If I not text before carriage, nothing occurs. Carriage not move to previous line.

Thanks.

**Comment by xdrop** [comment]
Do you consider indentation as line beginning?

eg. `____|Hello world` where `_` marks space and `|` marks the cursor

Or should this only occur in cases like
`|Hello world`

**Comment by Kristinita** [comment]
@xdrop , yes, I need remove all spaces and tabs in line beginning, but no move carriage in previous lime. So I need this function.

Thanks.

**Comment by xdrop** [comment]
@Kristinita 
ATM, I've added an option for this 

> It would be nice, if you add command to run backspace command only if carriage is not in line beginning.

The backspace will not trigger if there is no text before the cursor but will erase any sort of spacing before the cursor.

I assume this will be implemented by your macro? (Delete all text to line begin)

> If I have text before carriage, all text before carriage was deleted, carriage move to beginning of line.

Let me know if that's all so that I can merge the commit.

**Comment by Kristinita** [comment]
> The backspace will not trigger if there is no text before the cursor but will erase any sort of spacing before the cursor.

Yes, all right.

**Comment by Kristinita** [comment]
@xdrop, I'm sorry, how it's worked? I change my `Hungry Backspace.sublime-settings` and `hungry_backspace.py` files → I restart Sublime Text → but I have still behavior, if I press <kbd>Ctrl+Shift+Backspace</kbd>.

Thanks.

**Comment by xdrop** [comment]
@Kristinita I'm not able to replicate the problem. Is your <kbd>Ctrl+Shift+Backspace</kbd> mapped to the hungry backspace or the default sublime backspace?

Also can you try to remove the Package Control version in case they are conflicting and use the files from db4d385127d22d8c0d04ab9b1e8a3887863c6b6a ?

**Comment by Kristinita** [comment]
@xdrop, I think, how `disable_on_line_begin` worked.

+ If after line beginning I have a symbols, if i run `hungry_backspace` command, backspace disable for me. It is expected behavior.
+ But if line is blank, if I run `hungry_backspace` command, carriage still move to previous line. It is not expected behavior.

![hungry_backspace](http://i.imgur.com/sov8PYe.gif)

Thanks.

**Comment by xdrop** [comment]
@Kristinita Can you try again with 09974ad ?

**Comment by Kristinita** [comment]
@xdrop, thanks, it's work!

### 1. Request

May you add separate trigger for `disabled_on_line_begin = true` backspace?

### 2. Justification

Usually I don't need `disabled_on_line_begin = true`, it only hinders. By I need `disabled_on_line_begin = true` for my macros.

I want that I and others users of my macros can run my macros even if `disabled_on_line_begin = false` in our settings. I think, the best solution — is created separate trigger for `disabled_on_line_begin = true`.

### 3. Expected behavior

1. If I run `hungry_backspace` command, — <kbd>Backspace</kbd> by default — command run as `disable_on_line_begin = false`.
2. If I run `hungry_backspace_disable_on_line_begin` command — for example, <kbd>Super+Backspace</kbd> by default — command run as `disable_on_line_begin = true`.

Thanks.

**Comment by Kristinita** [comment]
@xdrop , actually.

Thanks.
