### ISSUE TITLE
Breaks hungry backspace when deleting first character of auto-completed pair of brackets/parentheses/quotes

### ISSUE THREAD

**Issue by taylorthurlow** [xdrop/Hungry-Backspace#4]
Default ST3 behavior is to automatically add a closing character when inserting a character like a quote, parentheses, bracket, etc. This works as expected, but now, for example, if you insert a left bracket, ST3 inserts the right bracket. At this point your cursor is between both brackets. I should be able to hit backspace and have BOTH brackets be deleted. This is default ST3 behavior but Hungry Backspace breaks this - only the first bracket is deleted.

**Comment by xdrop** [comment]
I can't reproduce the expected default ST3 behaviour. For me even if I disable Hungry Backspace and hit backspace only the left bracket gets deleted

**Comment by taylorthurlow** [comment]
Here's a gif animation of me showing the behavior as I enable and disable Hungry Backspace.

I am quite sure that it is default ST3 behavior to delete both characters in the pair.

EDIT: I should mention that perhaps you weren't able to replicate this behavior because it only does it contextually - try doing it in a variable declaration or function call like I do in the gif.

![output](https://cloud.githubusercontent.com/assets/761640/24581593/32b46b08-16d3-11e7-8121-024a182a588a.gif)

**Comment by xdrop** [comment]
@taylorthurlow Thanks I managed to reproduce it. I'll add a fix for this soon

**Comment by taylorthurlow** [comment]
Great to hear, thanks!
